{
 "title": "CNI Comparison",
 "time": { "from": "2019-07-08T23:53:54.000Z", "to": "2019-07-09T00:03:54.000Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"kube-system\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{namespace=\"kube-system\", workload=\"aws-node\", workload_type=\"daemonset\"}\n)\n",
     "legendFormat": "awsvpc"
    },
    {
     "expr": "sum(\n  label_replace(\n    namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"kube-system\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{namespace=\"kube-system\", workload=~\"calico-.*\", workload_type=\"daemonset\"}\n)\n",
     "legendFormat": "calico"
    },
    {
     "expr": "sum(\n  label_replace(\n    namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"kube-system\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{namespace=\"kube-system\", workload=\"weave-net\", workload_type=\"daemonset\"}\n)\n",
     "legendFormat": "weavenet"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    container_memory_usage_bytes{namespace=\"kube-system\", container_name!=\"\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{namespace=\"kube-system\", workload=\"aws-node\", workload_type=\"daemonset\"}\n  )\n",
     "legendFormat": "awsvpc"
    },
    {
     "expr": "sum(\n  label_replace(\n    container_memory_usage_bytes{namespace=\"kube-system\", container_name!=\"\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{namespace=\"kube-system\", workload=~\"calico-.*\", workload_type=\"daemonset\"}\n  )\n",
     "legendFormat": "calico"
    },
    {
     "expr": "sum(\n  label_replace(\n    container_memory_usage_bytes{namespace=\"kube-system\", container_name!=\"\"},\n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n  ) * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{namespace=\"kube-system\", workload=\"weave-net\", workload_type=\"daemonset\"}\n  )\n",
     "legendFormat": "weavenet"
    }
   ]
  },
  {
   "title": "gRPC Messages Per Second",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_messages_sent[$interval]))",
     "legendFormat": "awsvpc"
    },
    {
     "expr": "sum(rate(grpc_messages_sent[$interval]))",
     "legendFormat": "calico"
    },
    {
     "expr": "sum(rate(grpc_messages_sent[$interval]))",
     "legendFormat": "weavenet"
    }
   ]
  }
 ]
}